"""v1.0.3

Revision ID: 0abc80edb8db
Revises: a3af097384c6
Create Date: 2024-03-27 10:48:20.215504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abc80edb8db'
down_revision = 'a3af097384c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbInterfaceInvokeLog', schema=None) as batch_op:
        batch_op.drop_column('tStartTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbInterfaceInvokeLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tStartTime', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
