"""v1.0.2

Revision ID: a3af097384c6
Revises: 9cca611b2e3c
Create Date: 2024-03-26 17:23:56.140587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3af097384c6'
down_revision = '9cca611b2e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbInterfaceInvokeLog', schema=None) as batch_op:
        batch_op.drop_column('error_data')
        batch_op.drop_column('tEndTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbInterfaceInvokeLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tEndTime', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('error_data', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
