"""v1.0.0

Revision ID: db90f452c4f7
Revises: 
Create Date: 2024-03-26 16:58:46.800042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db90f452c4f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pbInterfaceInvokeLog',
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_name', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_uuid', sa.String(length=50), nullable=True),
    sa.Column('modify_name', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('guid', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('sFrom', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('sTo', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('sType', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('sKey', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('sData', sa.UnicodeText(), nullable=False),
    sa.Column('tCreateTime', sa.DateTime(), nullable=False),
    sa.Column('iExecResult', sa.Integer(), nullable=False),
    sa.Column('sResult', sa.UnicodeText(), nullable=False),
    sa.Column('error_data', sa.UnicodeText(), nullable=True),
    sa.Column('tEndTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pbInterfaceInvokeLog')
    # ### end Alembic commands ###
