"""v1.0.4

Revision ID: eb6077695684
Revises: 0abc80edb8db
Create Date: 2024-03-27 10:50:05.791959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6077695684'
down_revision = '0abc80edb8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbInterfaceInvokeLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kResult', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbInterfaceInvokeLog', schema=None) as batch_op:
        batch_op.drop_column('kResult')

    # ### end Alembic commands ###
